language: cpp
os: linux
env:
  - BAZEL_VERSION=3.1.0
before_install:
  - chmod +x scripts/install_bazel.sh
  - scripts/install_bazel.sh
script:
  # build all targets in all subdirectories
  - bazel build ...
  - bazel test ...
